/*
Scenario: Logging System
Description: An application where log messages are generated by a single source (producer) and processed by a logger (consumer).
*/

package main

import (
	"fmt"
	"time"
)

func main() {
	logCh := make(chan string)

	// Producer: Log message generator
	go func() {
		for i := 0; i < 10; i++ {
			logCh <- fmt.Sprintf("Log message %d", i)
			time.Sleep(time.Second)
		}
		close(logCh)
	}()

	// Consumer: Logger
	for msg := range logCh {
		fmt.Println("Logging: ", msg)
	}
}
